[zram0]
# Sets zram size to 50% of your total physical RAM
zram-size = ram / 2

# Uses zstd for superior memory compression ratio
compression-algorithm = zstd

# High priority ensures zram is used before any physical disk swap
swap-priority = 100
